config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'production_house#index', :as => :dashboard
  get 'production_house/:id/show' => 'production_house#show', :as => :production_house_show
  get 'production_house/:id/edit' => 'production_house#edit', :as => :production_house_edit
  patch 'production_house/:id/update' => 'production_house#update', :as => :production_house_update
  get 'movie/new_movie_seed_request' => 'movie#new_movie_seed_request', :as => :seed_new_movie_request
  post 'movie/seed_request_for_movie' => 'movie#seed_request_for_movie', :as => :seed_movie_data_api

end

app/models/production_house.rb
# == Schema Information
#
# Table name: production_houses
#
#  id              :bigint(8)        not null, primary key
#  ph_name         :string
#  ph_country      :string
#  ph_headquarters :string
#  ph_description  :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ph_homepage_url :string
#  ph_logo_path    :string
#  ph_tmdb_id      :integer
#

class ProductionHouse < ApplicationRecord

  # ActiveRecord Association Declarations Goes Here.....
  has_many :director_creations
  has_many :directors, through: :director_creations
  has_many :creations
  has_many :movies, through: :creations

  # ActiveRecord Validation Declarations Goes Here.....
  validates :ph_name, presence: true, uniqueness: true

  #ActiveRecord Callback Declarations Goes Here.....
  before_save :set_logo_url, on: [:create_prod_house_from_response]

  # All Instance and Class Method Declaration Goes Here.....
  # Method Declarations Starting with an 'self.' in Signature are all Class Methods.....

  def self.create_prod_house_from_response(ph_payload)
    prod_house_indexes = []
    if ph_payload.present?
      ph_payload.each do |phpl|
        SeedMovieLog.info("Stripping out all parameters from production house data payload recieved")
        prod_house_name = phpl.name if phpl.name.present?
        prod_house_country = phpl.origin_country if phpl.origin_country.present?
        prod_house_hq = phpl.headquarters if phpl.headquarters.present?
        prod_house_desc = phpl.description if phpl.description.present?
        prod_house_homepage = phpl.homepage if phpl.homepage.present?
        prod_house_logo_path = phpl.logo_path if phpl.logo_path.present?
        prod_house_tmdb_id = phpl.id if phpl.id.present?
        if ProductionHouse.find_by_ph_tmdb_id(prod_house_tmdb_id).present?
          SeedMovieLog.info("Record Exists for Production House #{prod_house_name}")
          prod_house_indexes << ProductionHouse.find_by_ph_tmdb_id(prod_house_tmdb_id).id
        else
          SeedMovieLog.info("Attempting to save record for #{prod_house_name}")
          prod_house = ProductionHouse.create(:ph_name => prod_house_name, :ph_country => prod_house_country, :ph_headquarters => prod_house_hq, :ph_description => prod_house_desc, :ph_homepage_url => prod_house_homepage , :ph_logo_path => prod_house_logo_path, :ph_tmdb_id => prod_house_tmdb_id)
          SeedMovieLog.info("Saved record for #{prod_house_name}") if prod_house.persisted?
          prod_house_indexes << prod_house.id
        end
      end
    end
    SeedMovieLog.info("No Production House Found for Movie. Bailing out with Fallback Mechanism") if prod_house_indexes.empty?
    prod_house_indexes << fetch_fallback_prodhouse_record if prod_house_indexes.empty? # Used as a fallback mechanism record for associating between Movie and ProductionHouse records in case we fail to fetch any production house information for the movie being seeded.
    return prod_house_indexes
  end

  def fetch_fallback_prodhouse_record
    ProductionHouse.find_by(:ph_name => 'NoProdHouse').id
  end

  private

  def set_logo_url
    unless self.ph_logo_path.nil?
      self.ph_logo_path = PROD_HOUSE_BASE_URL + ph_logo_path
    end
  end

end

app/controllers/production_house_controller.rb
class ProductionHouseController < ApplicationController

  def index
    @prod_houses = ProductionHouse.all.limit(15)
  end

  def show
    @prod_house = ProductionHouse.find_by_id(params[:id])
  end

  def edit
    @prod_house = ProductionHouse.find_by_id(params[:id])
  end

  def update

    @prod_house = ProductionHouse.find_by_id(params[:id])

    if @prod_house.update_attributes(prod_house_params_update)
      flash.now[:success] = 'Update Request Was Successful.'
      render "show"
    else
      flash.now[:warning] = 'Update Request Has Failed.Try Again.'
      render "edit"
    end

  end

  private

  def prod_house_params_update
    params.require(:production_house).permit(:ph_name, :ph_headquarters, :ph_establishment_year, :ph_description)
  end

end

app/helpers/production_house_helper.rb
module ProductionHouseHelper

  def fill_up_blank_values_ph_year(ph)

    if ph.ph_establishment_year.nil?
      return "Not Applicable"
    else
      return ph.ph_establishment_year
    end

  end

end

app/views/production_house/edit.html.slim
doctype html

- unless @prod_house.nil?

  p.text-warning Editing Production House Data for <i>'#{@prod_house.ph_name}'</i>

  = form_for @prod_house, :html => {:class => "form-horizontal center"}, :url => production_house_update_path(@prod_house), method: :patch do |f|

    .form-group
      = f.label :ph_name, "Production House Name", class: "col-md-4 control-label"
      .col-md-8
        = f.text_field :ph_name, class: "form-control"

    .form-group
      = f.label :ph_headquarters, "Production House Headquarters", class: "col-md-4 control-label"
      .col-md-8
        = f.text_field :ph_headquarters, class: "form-control"

    .form-group
      = f.label :ph_establishment_year, "Production House Establishment Year", class: "col-md-4 control-label"
      .col-md-8
        = f.text_field :ph_establishment_year, class: "form-control"

    .form-group
      = f.label :ph_description, "Production House Description", class: "col-md-4 control-label"
      .col-md-8
        = f.text_area :ph_description, class: "form-control"

    br

      = f.submit "Edit Production House Data", class: "btn btn-danger"

- else

  p.text-warning
    | No Production House Data Available For Editing. Please Try Again Later. Thank You!

app/views/production_house/index.html.slim
doctype html

h1. List of Production Houses

- unless @prod_houses.empty?

    table.table.table-bordered
      thead
        tr.table-warning
          th Production House Name
          th Production House Country
          th Production House HeadQuarters
          /!th Production House Establishment Year

      - @prod_houses.each do |prod_house|
        tbody
          tr.table-success
            td.name = prod_house.ph_name
            td.description = prod_house.ph_country
            td.headquarters = prod_house.ph_headquarters
            /!td.establishment_year = fill_up_blank_values_ph_year(prod_house)
- else

  p.text-danger
    | No Production Houses found. Please Try Again Later. Thank you!

app/views/production_house/show.html.slim
doctype html

- unless @prod_house.nil?

  h5 Kindly Find Details Listed Below For Production House <i> '#{@prod_house.ph_name}' </i>

  br

  table.table.table-bordered

    tr
      th.table-dark Name
      td = @prod_house.ph_name

    tr
      th.table-dark Description
      td = @prod_house.ph_description

    tr
      th.table-dark Establishment Year
      td = @prod_house.ph_establishment_year

    tr
      th.table-dark Headquarters
      td = @prod_house.ph_headquarters

    tr
      th.table-dark Country
      td = @prod_house.ph_country

- else

  p.text-warning
    | No Production House Data Found. Please Try Again Later. Thank you!